Ft routine full screen
josemak25/hairx-client pull request #24
Opened 2020-05-04 13:29 UTC by chidiogo-akunne

#### What does this PR do?

Show full routine details
![IMG_2740](https://user-images.githubusercontent.com/51112934/80970813-ae6b1e80-8e13-11ea-8b56-b0afe1448603.PNG)
![IMG_2739](https://user-images.githubusercontent.com/51112934/80970821-b1660f00-8e13-11ea-9538-8d2b404ca66b.PNG)

#### How should this be manually tested?

After cloning the repo,
`CD` into it and `RUN`

javascript
git checkout develop

git pull origin develop

yarn install

yarn test

Using an emulator: Launch the app, and you should see the home screen after loading.

#### Screenshots (if appropriate)

2020-05-04 13:35 UTC, ogbodo commented
Why two screen shots of same intention. Is it on purpose?

2020-05-04 13:49 UTC, ogbodo requested changes

2020-05-04 13:49 UTC, ogbodo commented on src/screens/regimen/regimen_routine/index.tsx
> +import { ScrollView, StatusBar, Platform, View } from 'react-native';
remove unused imports => Platform, View

2020-05-04 13:49 UTC, ogbodo commented on src/screens/regimen/regimen_routine/styles.ts
> +  position: absolute;
Always try using flex to arrange component in other  take full advantage of responsiveness across all screen sizes.

2020-05-04 13:49 UTC, ogbodo commented on src/screens/regimen/regimen_routine/styles.ts
> +  position: absolute;
Always try using flex to arrange component in other take full advantage of responsiveness across all screen sizes.

2020-05-04 14:19 UTC, ogbodo requested changes

2020-05-04 14:19 UTC, ogbodo commented on src/screens/regimen/regimen_routine/index.tsx
> +export default function RegimenRoutineScreen(props: RegimenRoutineScreenProp) {
```suggestion
export default function RegimenRoutineDetailScreen(props: RegimenRoutineScreenProp) {
```

2020-05-04 14:19 UTC, ogbodo commented on src/screens/regimen/regimen_routine/styles.ts
> +  font-size: ${({ theme }) => theme.fonts.SMALL_SIZE};
Please add unit here

2020-05-04 14:19 UTC, ogbodo commented on src/screens/regimen/regimen_routine/styles.ts
> +  font-family: ${({ theme }) => theme.fonts.JOST_BOOK};
here too

2020-05-04 14:19 UTC, ogbodo commented on src/screens/regimen/regimen_routine/styles.ts
> +  font-size: ${({ theme }) => theme.fonts.LARGE_SIZE};
here too

2020-05-04 14:19 UTC, ogbodo commented on src/screens/regimen/regimen_routine/styles.ts
> +  font-size: ${({ theme }) => theme.fonts.MEDIUM_SIZE};
here too

2020-05-04 14:19 UTC, ogbodo commented on src/screens/regimen/regimen_routine/styles.ts
> +  font-size: ${({ theme }) => theme.fonts.SMALL_SIZE};
here too, and every other places that you are supposed to add it.

2020-05-04 14:19 UTC, ogbodo commented on src/screens/regimen/regimen_routine/styles.ts
> +export const PriceSub = styled.Text`
```suggestion
export const PriceSuperscript = styled.Text`
```

2020-05-04 14:19 UTC, ogbodo commented on src/libs/recommendedProducts.ts
> +    subPrice: '74',
```suggestion
    priceSuperscript: '74',
```

2020-05-04 14:24 UTC, ogbodo requested changes

2020-05-04 14:24 UTC, ogbodo commented on src/screens/regimen/regimen_routine/styles.ts
> +export const Night = styled.Text`
```suggestion
export const Period = styled.Text`
```

2020-05-04 14:24 UTC, ogbodo commented on src/screens/regimen/regimen_routine/styles.ts
> +  font-family: ${({ theme }) => theme.fonts.CORMORANT_MEDIUM};
```suggestion
  font-family: ${({ theme }) => theme.fonts.CORMORANT_REGULAR};
```

2020-05-04 14:37 UTC, chidiogo-akunne commented on src/screens/regimen/regimen_routine/index.tsx
> +import { ScrollView, StatusBar, Platform, View } from 'react-native';
Done

2020-05-05 09:40 UTC, ogbodo approved these changes

2020-05-06 07:40 UTC, closed without merging